markdown: kramdown

baseurl: /

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  repository:
     output: true

defaults:
  -
    scope:
      path: "googlef0f8f70642b2ad70.html"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "repository"
    values:
      layout: "default"